
# Generated by Hermit; START; DO NOT EDIT.
if status is-interactive
  set -q HERMIT_ROOT_BIN; or set HERMIT_ROOT_BIN $HOME/bin/hermit
  eval "$(test -x $HERMIT_ROOT_BIN && $HERMIT_ROOT_BIN shell-hooks --print --fish)"
end
# Generated by Hermit; END; DO NOT EDIT.
